In [1]:
import torch

In [2]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5])
print(t[1:-1])
print()

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.])
tensor([1., 2., 3., 4., 5.])



In [7]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[3.,4.,5.]])
print(t)
print(t.dim())
print(t.size())
print(t.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [3., 4., 5.]])
2
torch.Size([3, 3])
torch.Size([3, 3])


In [10]:
#SUM
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0)) #행 방향으로 더함
print(t.sum(dim=1)) #열 방향으로 더함
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [11]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [12]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) #unsqueeze

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [13]:
print(ft.view(1,-1)) #reshape

tensor([[0., 1., 2.]])


In [16]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [17]:
bt = torch.ByteTensor([True, False,False, True])

In [18]:
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [19]:
print(bt.long())

tensor([1, 0, 0, 1])


In [20]:
print(bt.float())

tensor([1., 0., 0., 1.])


In [22]:
#Concatenate
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [23]:
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [24]:
print(torch.cat([x,y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [25]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [26]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [27]:
#torch.ones_like()
#torch.zeros_like()

In [29]:
# In-place Operation
x = torch.FloatTensor([[1,2,],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
